image: marcoturi/ionic:latest

stages:
  - deploy

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

# build android apk file
build_android:
  stage: deploy
  only:
    - master
  script:
    - ls
    - npm i
    - ionic cordova platform rm android
    - ionic cordova platform add android
    - ionic cordova build android 
  artifacts:
    paths:
      - platforms/android/app/build/outputs/apk/UntouchedApp.apk

#build ios apk file
#build_ios:
#  stage: deploy
#  only:
#    - master
#  script:
#    - ls
#    - npm i
#    - ionic cordova platform rm ios
#    - ionic cordova platform add ios
#    - ionic cordova build ios
#  artifacts:
#    paths:
#      - platforms/android/app/build/outputs/ipa
