stages:
  - deploy

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

build_android:
  stage: deploy
  only:
    - master
  script:
    - ls
    - npm i
    - ionic cordova platform rm android
    - ionic cordova platform add android
    - ionic cordova build android
    - ls ./platforms/android/build/outputs/apk/android*.apk
  artifacts:
    paths:
      - platforms/android/build/outputs/apk

build_ios:
  stage: deploy
  only:
    - master
  script:
    - ls
    - npm i
    - ionic cordova platform rm ios
    - ionic cordova platform add ios
    - ionic cordova build ios
    - ls ./platforms/ios/build/outputs/apk/ios*.ipa
  artifacts:
    paths:
      - platforms/ios/build/outputs/ipa
  